[build]
  publish = "build"
  command = "CI=false npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify Blob storage
[functions]
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
