[build]
  publish = "build"
  command = "CI=false npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Configure functions to use Node.js 20 for full compatibility
[functions]
  node_bundler = "esbuild"
  [functions.environment]
    NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
